
//#define SPROUT_CONFIG_DISABLE_CONSTEXPR
//#define SPROUT_CONFIG_DISABLE_NOEXCEPT
//#define SPROUT_CONFIG_DISABLE_TEMPLATE_ALIASES
//#define SPROUT_CONFIG_USE_SSCRISK_CEL
//#define SPROUT_CONFIG_DISABLE_SUPPORT_TEMPORARY_CONTAINER_ITERATION
//#define SPROUT_CONFIG_SUPPORT_TEMPORARY_CONTAINER_ITERATION
