#ifndef SPROUT_RANGE_ALGORITHM_NON_MODIFYIING_HPP
#define SPROUT_RANGE_ALGORITHM_NON_MODIFYIING_HPP

#include <sprout/config.hpp>
//#include <sprout/range/algorithm/all_of.hpp>
//#include <sprout/range/algorithm/any_of.hpp>
//#include <sprout/range/algorithm/none_of.hpp>
//#include <sprout/range/algorithm/find.hpp>
//#include <sprout/range/algorithm/find_if.hpp>
//#include <sprout/range/algorithm/find_if_not.hpp>
//#include <sprout/range/algorithm/find_end.hpp>
//#include <sprout/range/algorithm/find_first_of.hpp>
//#include <sprout/range/algorithm/adjacent_find.hpp>
//#include <sprout/range/algorithm/count.hpp>
//#include <sprout/range/algorithm/count_if.hpp>
//#include <sprout/range/algorithm/mismatch.hpp>
//#include <sprout/range/algorithm/equal.hpp>
//#include <sprout/range/algorithm/is_permutation.hpp>
//#include <sprout/range/algorithm/search.hpp>
//#include <sprout/range/algorithm/search_n.hpp>
//#include <sprout/range/algorithm/is_partitioned.hpp>
//#include <sprout/range/algorithm/partition_point.hpp>
//#include <sprout/range/algorithm/is_sorted.hpp>
//#include <sprout/range/algorithm/is_sorted_until.hpp>
//#include <sprout/range/algorithm/lower_bound.hpp>
//#include <sprout/range/algorithm/upper_bound.hpp>
//#include <sprout/range/algorithm/equal_range.hpp>
//#include <sprout/range/algorithm/binary_search.hpp>
//#include <sprout/range/algorithm/includes.hpp>
//#include <sprout/range/algorithm/is_heap.hpp>
//#include <sprout/range/algorithm/is_heap_until.hpp>
//#include <sprout/range/algorithm/min.hpp>
//#include <sprout/range/algorithm/max.hpp>
//#include <sprout/range/algorithm/minmax.hpp>
//#include <sprout/range/algorithm/min_element.hpp>
//#include <sprout/range/algorithm/max_element.hpp>
//#include <sprout/range/algorithm/minmax_element.hpp>
//#include <sprout/range/algorithm/lexicographical_compare.hpp>

#endif	// #ifndef SPROUT_RANGE_ALGORITHM_NON_MODIFYIING_HPP
