#ifndef SPROUT_PREPROCESSOR_STRINGIZE_HPP
#define SPROUT_PREPROCESSOR_STRINGIZE_HPP

#include <sprout/config.hpp>

//
// SPROUT_PP_STRINGIZE
//
#define SPROUT_PP_STRINGIZE(text) SPROUT_PP_STRINGIZE_I(text)
#define SPROUT_PP_STRINGIZE_I(text) #text

#endif	// #ifndef SPROUT_PREPROCESSOR_STRINGIZE_HPP

