#ifndef SPROUT_PREPROCESSOR_WSTRINGIZE_HPP
#define SPROUT_PREPROCESSOR_WSTRINGIZE_HPP

#include <sprout/config.hpp>

//
// SPROUT_PP_WSTRINGIZE
//
#define SPROUT_PP_WSTRINGIZE(text) SPROUT_PP_WSTRINGIZE_I(text)
#define SPROUT_PP_WSTRINGIZE_I(text) SPROUT_PP_WSTRINGIZE_II(#text)
#define SPROUT_PP_WSTRINGIZE_II(str) L ## str

#endif	// #ifndef SPROUT_PREPROCESSOR_WSTRINGIZE_HPP
