/*=============================================================================
  Copyright (c) 2011-2016 Bolero MURAKAMI
  https://github.com/bolero-MURAKAMI/Sprout

  Distributed under the Boost Software License, Version 1.0. (See accompanying
  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
=============================================================================*/
#ifndef SPROUT_CONFIG_USER_HPP
#define SPROUT_CONFIG_USER_HPP

//
// 言語機能を無効化するコンフィグ
//	ユーザ定義されない場合、処理系に応じて自動的に定義される。
//
//#define SPROUT_CONFIG_DISABLE_CONSTEXPR
//#define SPROUT_CONFIG_DISABLE_CXX14_CONSTEXPR
//#define SPROUT_CONFIG_DISABLE_DEFAULTED_FUNCTIONS
//#define SPROUT_CONFIG_DISABLE_DELETED_FUNCTIONS
//#define SPROUT_CONFIG_DISABLE_EXPLICIT_CONVERSION_OPERATORS
//#define SPROUT_CONFIG_DISABLE_NOEXCEPT
//#define SPROUT_CONFIG_DISABLE_TEMPLATE_ALIASES
//#define SPROUT_CONFIG_DISABLE_USER_DEFINED_LITERALS
//#define SPROUT_CONFIG_DISABLE_DELEGATING_CONSTRUCTORS
//#define SPROUT_CONFIG_DISABLE_UNICODE_LITERALS
//#define SPROUT_CONFIG_DISABLE_VARIABLE_TEMPLATES

//
// 言語機能を強制的に有効化するコンフィグ
//	SPROUT_CONFIG_DISABLE_*** の自動定義を抑制する。
//	SPROUT_CONFIG_DISABLE_*** がユーザ定義されている場合、無効化のほうが優先される。
//
//#define SPROUT_CONFIG_FORCE_CONSTEXPR
//#define SPROUT_CONFIG_FORCE_CXX14_CONSTEXPR
//#define SPROUT_CONFIG_FORCE_DEFAULTED_FUNCTIONS
//#define SPROUT_CONFIG_FORCE_DELETED_FUNCTIONS
//#define SPROUT_CONFIG_FORCE_EXPLICIT_CONVERSION_OPERATORS
//#define SPROUT_CONFIG_FORCE_NOEXCEPT
//#define SPROUT_CONFIG_FORCE_TEMPLATE_ALIASES
//#define SPROUT_CONFIG_FORCE_USER_DEFINED_LITERALS
//#define SPROUT_CONFIG_FORCE_DELEGATING_CONSTRUCTORS
//#define SPROUT_CONFIG_FORCE_UNICODE_LITERALS
//#define SPROUT_CONFIG_FORCE_VARIABLE_TEMPLATES

//
// 実装に外部ライブラリを使用するコンフィグ
//
//#define SPROUT_CONFIG_USE_SSCRISK_CEL

//
// 処理系機能を無効化するコンフィグ
//	ユーザ定義されない場合、処理系に応じて自動的に定義される。
//
//#define SPROUT_CONFIG_DISABLE_BUILTIN_CMATH_FUNCTION
//#define SPROUT_CONFIG_DISABLE_BUILTIN_COPYSIGN_FUNCTION
//#define SPROUT_CONFIG_DISABLE_BUILTIN_BIT_OPERATION

//
// 実装の詳細を切り替えるコンフィグ
//
//#define SPROUT_CONFIG_DISABLE_LARGE_FLOAT_ROUNDING
//#define SPROUT_CONFIG_DISABLE_SUPPORT_TEMPORARY_CONTAINER_ITERATION
//#define SPROUT_CONFIG_DISABLE_SUPPORT_EFFICIENT_ARRAY_ITERATION

#endif	// #ifndef SPROUT_CONFIG_USER_HPP
