#ifndef SPROUT_CONFIG_COMPILER_CXX11_HPP
#define SPROUT_CONFIG_COMPILER_CXX11_HPP

#ifdef SPROUT_NO_CONSTEXPR
#	define SPROUT_NO_CXX11_CONSTEXPR
#endif
#ifdef SPROUT_NO_NOEXCEPT
#	define SPROUT_NO_CXX11_CNOEXCEPT
#endif
#ifdef SPROUT_NO_TEMPLATE_ALIASES
#	define SPROUT_NO_CXX11_CTEMPLATE_ALIASES
#endif
#ifdef SPROUT_NO_USER_DEFINED_LITERALS
#	define SPROUT_NO_CXX11_CUSER_DEFINED_LITERALS
#endif
#ifdef SPROUT_NO_DELEGATING_CONSTRUCTORS
#	define SPROUT_NO_CXX11_CDELEGATING_CONSTRUCTORS
#endif

#endif	// #ifndef SPROUT_CONFIG_COMPILER_CXX11_HPP
