#ifndef SPROUT_CONFIG_COMPILER_DIGITALMARS_HPP
#define SPROUT_CONFIG_COMPILER_DIGITALMARS_HPP

#define SPROUT_NO_CXX11_CONSTEXPR
#define SPROUT_NO_CXX11_DEFAULTED_FUNCTIONS
#define SPROUT_NO_CXX11_DELETED_FUNCTIONS
#define SPROUT_NO_CXX11_EXPLICIT_CONVERSION_OPERATORS
#define SPROUT_NO_CXX11_NOEXCEPT
#define SPROUT_NO_CXX11_TEMPLATE_ALIASES
#define SPROUT_NO_CXX11_USER_DEFINED_LITERALS
#define SPROUT_NO_CXX11_DELEGATING_CONSTRUCTORS
#define SPROUT_NO_CXX11_UNICODE_LITERALS

#define SPROUT_NO_CXX14_CONSTEXPR

#endif	// #ifndef SPROUT_CONFIG_COMPILER_DIGITALMARS_HPP
