#ifndef SPROUT_CONFIG_COMPILER_HAS_FUTURE_HPP
#define SPROUT_CONFIG_COMPILER_HAS_FUTURE_HPP

#ifndef SPROUT_NO_CONSTEXPR
#	define SPROUT_HAS_CONSTEXPR
#endif
#ifndef SPROUT_NO_DEFAULTED_FUNCTIONS
#	define SPROUT_HAS_DEFAULTED_FUNCTIONS
#endif
#ifndef SPROUT_NO_DELETED_FUNCTIONS
#	define SPROUT_HAS_DELETED_FUNCTIONS
#endif
#ifndef SPROUT_NO_NOEXCEPT
#	define SPROUT_HAS_NOEXCEPT
#endif
#ifndef SPROUT_NO_TEMPLATE_ALIASES
#	define SPROUT_HAS_TEMPLATE_ALIASES
#endif
#ifndef SPROUT_NO_USER_DEFINED_LITERALS
#	define SPROUT_HAS_USER_DEFINED_LITERALS
#endif
#ifndef SPROUT_NO_DELEGATING_CONSTRUCTORS
#	define SPROUT_HAS_DELEGATING_CONSTRUCTORS
#endif
#ifndef SPROUT_NO_UNICODE_LITERALS
#	define SPROUT_HAS_UNICODE_LITERALS
#endif

#endif	// #ifndef SPROUT_CONFIG_COMPILER_HAS_FUTURE_HPP
