#ifndef SPROUT_CONFIG_COMPILER_PATHSCALE_HPP
#define SPROUT_CONFIG_COMPILER_PATHSCALE_HPP

#if __PATHCC__ >= 4
#	define SPROUT_NO_CONSTEXPR
#	define SPROUT_NO_NOEXCEPT
#	define SPROUT_NO_TEMPLATE_ALIASES
#	define SPROUT_NO_USER_DEFINED_LITERALS
#	define SPROUT_NO_DELEGATING_CONSTRUCTORS
#endif

#endif	// #ifndef SPROUT_CONFIG_COMPILER_PATHSCALE_HPP
