#ifndef SPROUT_CONFIG_COMPILER_VACPP_HPP
#define SPROUT_CONFIG_COMPILER_VACPP_HPP

#if !__IBMCPP_CONSTEXPR
#	define SPROUT_NO_CONSTEXPR
#endif
#define SPROUT_NO_DEFAULTED_FUNCTIONS
#define SPROUT_NO_DELETED_FUNCTIONS
#if !__IBMCPP_EXPLICIT_CONVERSION_OPERATORS
#	define SPROUT_NO_EXPLICIT_CONVERSION_OPERATORS
#endif
#define SPROUT_NO_NOEXCEPT
#define SPROUT_NO_TEMPLATE_ALIASES
#define SPROUT_NO_USER_DEFINED_LITERALS
#define SPROUT_NO_DELEGATING_CONSTRUCTORS
#define SPROUT_NO_UNICODE_LITERALS

#endif	// #ifndef SPROUT_CONFIG_COMPILER_VACPP_HPP
