#ifndef SPROUT_ALGORITHM_FIT_HPP
#define SPROUT_ALGORITHM_FIT_HPP

#include <sprout/config.hpp>
#include <sprout/algorithm/fit/copy.hpp>
#include <sprout/algorithm/fit/copy_n.hpp>
#include <sprout/algorithm/fit/copy_if.hpp>
#include <sprout/algorithm/fit/copy_backward.hpp>
#include <sprout/algorithm/fit/transform.hpp>
#include <sprout/algorithm/fit/replace.hpp>
#include <sprout/algorithm/fit/replace_if.hpp>
#include <sprout/algorithm/fit/replace_copy.hpp>
#include <sprout/algorithm/fit/replace_copy_if.hpp>
#include <sprout/algorithm/fit/fill.hpp>
#include <sprout/algorithm/fit/fill_n.hpp>
#include <sprout/algorithm/fit/generate.hpp>
#include <sprout/algorithm/fit/generate_n.hpp>
#include <sprout/algorithm/fit/unfold.hpp>
#include <sprout/algorithm/fit/unfold_n.hpp>
#include <sprout/algorithm/fit/recurrence.hpp>
#include <sprout/algorithm/fit/recurrence_n.hpp>
#include <sprout/algorithm/fit/remove.hpp>
#include <sprout/algorithm/fit/remove_if.hpp>
#include <sprout/algorithm/fit/remove_copy.hpp>
#include <sprout/algorithm/fit/remove_copy_if.hpp>
#include <sprout/algorithm/fit/unique.hpp>
#include <sprout/algorithm/fit/unique_copy.hpp>
#include <sprout/algorithm/fit/reverse.hpp>
#include <sprout/algorithm/fit/reverse_copy.hpp>
#include <sprout/algorithm/fit/rotate.hpp>
#include <sprout/algorithm/fit/rotate_copy.hpp>
#include <sprout/algorithm/fit/shuffle.hpp>
#include <sprout/algorithm/fit/shuffle_result.hpp>
#include <sprout/algorithm/fit/partition.hpp>
#include <sprout/algorithm/fit/partition_copy.hpp>
#include <sprout/algorithm/fit/stable_partition.hpp>
#include <sprout/algorithm/fit/stable_partition_copy.hpp>
#include <sprout/algorithm/fit/sort.hpp>
#include <sprout/algorithm/fit/stable_sort.hpp>
#include <sprout/algorithm/fit/partial_sort.hpp>
#include <sprout/algorithm/fit/nth_element.hpp>
#include <sprout/algorithm/fit/merge.hpp>
#include <sprout/algorithm/fit/inplace_merge.hpp>
#include <sprout/algorithm/fit/set_union.hpp>
#include <sprout/algorithm/fit/set_intersection.hpp>
#include <sprout/algorithm/fit/set_difference.hpp>
#include <sprout/algorithm/fit/set_symmetric_difference.hpp>
#include <sprout/algorithm/fit/push_heap.hpp>
#include <sprout/algorithm/fit/pop_heap.hpp>
#include <sprout/algorithm/fit/make_heap.hpp>
#include <sprout/algorithm/fit/make_partial_heap.hpp>
#include <sprout/algorithm/fit/sort_heap.hpp>
#include <sprout/algorithm/fit/next_permutation.hpp>
#include <sprout/algorithm/fit/prev_permutation.hpp>
#include <sprout/algorithm/fit/random_swap.hpp>
#include <sprout/algorithm/fit/random_swap_result.hpp>
#include <sprout/algorithm/fit/bogo_sort.hpp>
#include <sprout/algorithm/fit/bogo_sort_result.hpp>
#include <sprout/algorithm/fit/bozo_sort.hpp>
#include <sprout/algorithm/fit/bozo_sort_result.hpp>

#endif	// #ifndef SPROUT_ALGORITHM_FIT_HPP
