#ifndef SPROUT_ALGORITHM_INFIT_HPP
#define SPROUT_ALGORITHM_INFIT_HPP

#include <sprout/config.hpp>
#include <sprout/algorithm/infit/copy.hpp>
#include <sprout/algorithm/infit/copy_n.hpp>
#include <sprout/algorithm/infit/copy_if.hpp>
#include <sprout/algorithm/infit/copy_backward.hpp>
#include <sprout/algorithm/infit/transform.hpp>
#include <sprout/algorithm/infit/replace.hpp>
#include <sprout/algorithm/infit/replace_if.hpp>
#include <sprout/algorithm/infit/replace_copy.hpp>
#include <sprout/algorithm/infit/replace_copy_if.hpp>
#include <sprout/algorithm/infit/fill.hpp>
#include <sprout/algorithm/infit/fill_n.hpp>
#include <sprout/algorithm/infit/generate.hpp>
#include <sprout/algorithm/infit/generate_n.hpp>
#include <sprout/algorithm/infit/remove.hpp>
#include <sprout/algorithm/infit/remove_if.hpp>
#include <sprout/algorithm/infit/remove_copy.hpp>
#include <sprout/algorithm/infit/remove_copy_if.hpp>
#include <sprout/algorithm/infit/unique.hpp>
#include <sprout/algorithm/infit/unique_copy.hpp>
#include <sprout/algorithm/infit/reverse.hpp>
#include <sprout/algorithm/infit/reverse_copy.hpp>
#include <sprout/algorithm/infit/rotate.hpp>
#include <sprout/algorithm/infit/rotate_copy.hpp>
#include <sprout/algorithm/infit/partition.hpp>
#include <sprout/algorithm/infit/partition_copy.hpp>
#include <sprout/algorithm/infit/stable_partition.hpp>
#include <sprout/algorithm/infit/stable_partition_copy.hpp>
#include <sprout/algorithm/infit/sort.hpp>
#include <sprout/algorithm/infit/stable_sort.hpp>
#include <sprout/algorithm/infit/partial_sort.hpp>
#include <sprout/algorithm/infit/nth_element.hpp>
#include <sprout/algorithm/infit/merge.hpp>
#include <sprout/algorithm/infit/inplace_merge.hpp>
#include <sprout/algorithm/infit/set_union.hpp>
#include <sprout/algorithm/infit/set_intersection.hpp>
#include <sprout/algorithm/infit/set_difference.hpp>
#include <sprout/algorithm/infit/set_symmetric_difference.hpp>
#include <sprout/algorithm/infit/push_heap.hpp>
#include <sprout/algorithm/infit/pop_heap.hpp>
#include <sprout/algorithm/infit/make_heap.hpp>
#include <sprout/algorithm/infit/make_partial_heap.hpp>
#include <sprout/algorithm/infit/sort_heap.hpp>
#include <sprout/algorithm/infit/swap_element.hpp>
#include <sprout/algorithm/infit/swap_element_copy.hpp>

#endif	// #ifndef SPROUT_ALGORITHM_INFIT_HPP
