#ifndef SPROUT_ALGORITHM_OUTFIT_HPP
#define SPROUT_ALGORITHM_OUTFIT_HPP

#include <sprout/config.hpp>
#include <sprout/algorithm/outfit/copy.hpp>
#include <sprout/algorithm/outfit/copy_n.hpp>
#include <sprout/algorithm/outfit/copy_if.hpp>
#include <sprout/algorithm/outfit/copy_backward.hpp>
#include <sprout/algorithm/outfit/transform.hpp>
#include <sprout/algorithm/outfit/replace.hpp>
#include <sprout/algorithm/outfit/replace_if.hpp>
#include <sprout/algorithm/outfit/replace_copy.hpp>
#include <sprout/algorithm/outfit/replace_copy_if.hpp>
#include <sprout/algorithm/outfit/fill.hpp>
#include <sprout/algorithm/outfit/fill_n.hpp>
#include <sprout/algorithm/outfit/generate.hpp>
#include <sprout/algorithm/outfit/generate_n.hpp>
#include <sprout/algorithm/outfit/remove.hpp>
#include <sprout/algorithm/outfit/remove_if.hpp>
#include <sprout/algorithm/outfit/remove_copy.hpp>
#include <sprout/algorithm/outfit/remove_copy_if.hpp>
#include <sprout/algorithm/outfit/unique.hpp>
#include <sprout/algorithm/outfit/unique_copy.hpp>
#include <sprout/algorithm/outfit/reverse.hpp>
#include <sprout/algorithm/outfit/reverse_copy.hpp>
#include <sprout/algorithm/outfit/rotate.hpp>
#include <sprout/algorithm/outfit/rotate_copy.hpp>
#include <sprout/algorithm/outfit/partition.hpp>
#include <sprout/algorithm/outfit/partition_copy.hpp>
#include <sprout/algorithm/outfit/stable_partition.hpp>
#include <sprout/algorithm/outfit/stable_partition_copy.hpp>
#include <sprout/algorithm/outfit/sort.hpp>
#include <sprout/algorithm/outfit/stable_sort.hpp>
#include <sprout/algorithm/outfit/partial_sort.hpp>
#include <sprout/algorithm/outfit/nth_element.hpp>
#include <sprout/algorithm/outfit/merge.hpp>
#include <sprout/algorithm/outfit/inplace_merge.hpp>
#include <sprout/algorithm/outfit/set_union.hpp>
#include <sprout/algorithm/outfit/set_intersection.hpp>
#include <sprout/algorithm/outfit/set_difference.hpp>
#include <sprout/algorithm/outfit/set_symmetric_difference.hpp>
#include <sprout/algorithm/outfit/push_heap.hpp>
#include <sprout/algorithm/outfit/pop_heap.hpp>
#include <sprout/algorithm/outfit/make_heap.hpp>
#include <sprout/algorithm/outfit/make_partial_heap.hpp>
#include <sprout/algorithm/outfit/sort_heap.hpp>
#include <sprout/algorithm/outfit/swap_element.hpp>
#include <sprout/algorithm/outfit/swap_element_copy.hpp>

#endif	// #ifndef SPROUT_ALGORITHM_OUTFIT_HPP
