#ifndef SPROUT_CONFIG_STDLIB_LIBCPP_HPP
#define SPROUT_CONFIG_STDLIB_LIBCPP_HPP

#ifdef _LIBCPP_HAS_NO_VARIADICS
#	define SPROUT_NO_CXX11_HDR_TUPLE
#endif

#define SPROUT_NO_CXX11_HDR_CHRONO
#define SPROUT_NO_CXX11_HDR_FUTURE
#define SPROUT_NO_CXX11_HDR_TYPE_TRAITS
#define SPROUT_NO_CXX11_ATOMIC_SMART_PTR

#include <utility>
#if defined(_LIBCPP_VERSION) && (_LIBCPP_VERSION < 1101)
#	define SPROUT_NO_CXX11_CHAR_TRAITS
#endif

#endif	// #ifndef SPROUT_CONFIG_STDLIB_LIBCPP_HPP
