#ifndef SPROUT_CONFIG_STDLIB_SGI_HPP
#define SPROUT_CONFIG_STDLIB_SGI_HPP

#define SPROUT_NO_CXX11_HDR_ARRAY
#define SPROUT_NO_CXX11_HDR_CHRONO
#define SPROUT_NO_CXX11_HDR_CODECVT
#define SPROUT_NO_CXX11_HDR_CONDITION_VARIABLE
#define SPROUT_NO_CXX11_HDR_FORWARD_LIST
#define SPROUT_NO_CXX11_HDR_FUTURE
#define SPROUT_NO_CXX11_HDR_INITIALIZER_LIST
#define SPROUT_NO_CXX11_HDR_MUTEX
#define SPROUT_NO_CXX11_HDR_RANDOM
#define SPROUT_NO_CXX11_HDR_RATIO
#define SPROUT_NO_CXX11_HDR_REGEX
#define SPROUT_NO_CXX11_HDR_SYSTEM_ERROR
#define SPROUT_NO_CXX11_HDR_THREAD
#define SPROUT_NO_CXX11_HDR_TUPLE
#define SPROUT_NO_CXX11_HDR_TYPE_TRAITS
#define SPROUT_NO_CXX11_HDR_TYPEINDEX
#define SPROUT_NO_CXX11_HDR_UNORDERED_MAP
#define SPROUT_NO_CXX11_HDR_UNORDERED_SET
#define SPROUT_NO_CXX11_NUMERIC_LIMITS
#define SPROUT_NO_CXX11_ALLOCATOR
#define SPROUT_NO_CXX11_ATOMIC_SMART_PTR
#define SPROUT_NO_CXX11_SMART_PTR
#define SPROUT_NO_CXX11_HDR_FUNCTIONAL

#endif	// #ifndef SPROUT_CONFIG_STDLIB_SGI_HPP
